#!/bin/sh

echo ""
echo '* Verify dependencies'
go mod verify

echo ""
echo '* Install: golangci-lint'
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

echo ""
echo '* Run: golangci'
golangci-lint run ./...

echo ""
echo '* Run: go test'
go test -count=1 -timeout 30s $(go list ./... | grep -Ev 'cmd') -covermode=atomic